# Generated by Django 5.0.6 on 2024-06-21 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_note_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='tag',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
